from enum import Enum


class PermissionClaims(str, Enum):
    HOSTEDPUBLICCLOUDJOBCREATE = "HostedPublicCloudJobCreate"
    HOSTEDPUBLICCLOUDJOBDELETE = "HostedPublicCloudJobDelete"
    HOSTEDPUBLICCLOUDJOBEDIT = "HostedPublicCloudJobEdit"
    HOSTEDPUBLICCLOUDJOBENABLEDISABLE = "HostedPublicCloudJobEnableDisable"
    HOSTEDPUBLICCLOUDJOBSTARTSTOP = "HostedPublicCloudJobStartStop"
    HOSTEDPUBLICCLOUDRESTORE = "HostedPublicCloudRestore"
    HOSTEDVBM365JOBCREATE = "HostedVbm365JobCreate"
    HOSTEDVBM365JOBDELETE = "HostedVbm365JobDelete"
    HOSTEDVBM365JOBEDIT = "HostedVbm365JobEdit"
    HOSTEDVBM365JOBENABLEDISABLE = "HostedVbm365JobEnableDisable"
    HOSTEDVBM365JOBREPOSITORYWRITE = "HostedVbm365JobRepositoryWrite"
    HOSTEDVBM365JOBSCHEDULEWRITE = "HostedVbm365JobScheduleWrite"
    HOSTEDVBM365JOBSCOPEWRITE = "HostedVbm365JobScopeWrite"
    HOSTEDVBM365JOBSTARTSTOP = "HostedVbm365JobStartStop"
    HOSTEDVBM365RESTORE = "HostedVbm365Restore"
    HOSTEDVBRJOBCREATE = "HostedVbrJobCreate"
    HOSTEDVBRJOBDELETE = "HostedVbrJobDelete"
    HOSTEDVBRJOBEDIT = "HostedVbrJobEdit"
    HOSTEDVBRJOBENABLEDISABLE = "HostedVbrJobEnableDisable"
    HOSTEDVBRJOBGUESTPROCESSINGWRITE = "HostedVbrJobGuestProcessingWrite"
    HOSTEDVBRJOBRETENTIONWRITE = "HostedVbrJobRetentionWrite"
    HOSTEDVBRJOBSCHEDULEWRITE = "HostedVbrJobScheduleWrite"
    HOSTEDVBRJOBSCOPEWRITE = "HostedVbrJobScopeWrite"
    HOSTEDVBRJOBSTARTSTOP = "HostedVbrJobStartStop"
    HOSTEDVBRJOBSTORAGEWRITE = "HostedVbrJobStorageWrite"
    REMOTEPUBLICCLOUDJOBENABLEDISABLE = "RemotePublicCloudJobEnableDisable"
    REMOTEPUBLICCLOUDJOBSTARTSTOP = "RemotePublicCloudJobStartStop"
    REMOTEVBM365JOBCREATE = "RemoteVbm365JobCreate"
    REMOTEVBM365JOBDELETE = "RemoteVbm365JobDelete"
    REMOTEVBM365JOBEDIT = "RemoteVbm365JobEdit"
    REMOTEVBM365JOBENABLEDISABLE = "RemoteVbm365JobEnableDisable"
    REMOTEVBM365JOBREPOSITORYWRITE = "RemoteVbm365JobRepositoryWrite"
    REMOTEVBM365JOBSCHEDULEWRITE = "RemoteVbm365JobScheduleWrite"
    REMOTEVBM365JOBSCOPEWRITE = "RemoteVbm365JobScopeWrite"
    REMOTEVBM365JOBSTARTSTOP = "RemoteVbm365JobStartStop"
    REMOTEVBM365RESTORE = "RemoteVbm365Restore"
    REMOTEVBRJOBDELETE = "RemoteVbrJobDelete"
    REMOTEVBRJOBEDIT = "RemoteVbrJobEdit"
    REMOTEVBRJOBENABLEDISABLE = "RemoteVbrJobEnableDisable"
    REMOTEVBRJOBSTARTSTOP = "RemoteVbrJobStartStop"

    def __str__(self) -> str:
        return str(self.value)
